name: resume_templates_push
on:
  push:
    branches:
      - main

jobs:
  compile_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install LaTeX distribution
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends texlive-xetex texlive-fonts-recommended texlive-plain-generic 

      - name: download font dependencies
        run: |
          curl "https://mirror.quantum5.ca/CTAN/fonts/tex-gyre.zip" --output tex-gyre.zip

      - name: install font dependencies
        run: |
          unzip tex-gyre.zip  
          cp tex-gyre/opentype/*.otf /usr/share/fonts
          fc-cache -f -v
          mkdir -p output

      - name: compile career developer resume
        run: |
          xelatex -output-directory=output main.tex
        working-directory: ./career_developer_template
        
      - name: compile general template
        run: |
          xelatex -output-directory=output main.tex
        working-directory: ./general_template
        
      - name: compile junior developer template
        run: |
          xelatex -output-directory=output main.tex
        working-directory: ./junior_developer_template
        
      - name: compile cover letter
        run: |
          xelatex -output-directory=output main.tex
        working-directory: ./cover_letter
        
      - name: Compile references
        run: |
          xelatex -output-directory=output main.tex
        working-directory: ./references

      - name: move PDFs to examples directory
        run: |
          mkdir -p examples
          mv output/*.pdf examples/

      - name: commit and push PDFs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add examples/*
          git commit -m "Update example PDFs" || echo "No changes to commit"
          git push